// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBix0XxWE08Vpgh7-dkRloOy5kzjvJ0TJ0',
    appId: '1:833914734243:web:4e5aa38c656c4f95b76116',
    messagingSenderId: '833914734243',
    projectId: 'flutter-projects-b9531',
    authDomain: 'flutter-projects-b9531.firebaseapp.com',
    storageBucket: 'flutter-projects-b9531.firebasestorage.app',
    measurementId: 'G-CN1V2EPE5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsqhH0Byy3nXFiWSN5lVtmHXc_9QWRYo',
    appId: '1:833914734243:android:aa221c3907a85ce6b76116',
    messagingSenderId: '833914734243',
    projectId: 'flutter-projects-b9531',
    storageBucket: 'flutter-projects-b9531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtL57-H_dYP2dutDMeqCrRqXJKQ0Tts9I',
    appId: '1:833914734243:ios:e8a26397175760f8b76116',
    messagingSenderId: '833914734243',
    projectId: 'flutter-projects-b9531',
    storageBucket: 'flutter-projects-b9531.firebasestorage.app',
    iosBundleId: 'com.example.uiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtL57-H_dYP2dutDMeqCrRqXJKQ0Tts9I',
    appId: '1:833914734243:ios:e8a26397175760f8b76116',
    messagingSenderId: '833914734243',
    projectId: 'flutter-projects-b9531',
    storageBucket: 'flutter-projects-b9531.firebasestorage.app',
    iosBundleId: 'com.example.uiKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBix0XxWE08Vpgh7-dkRloOy5kzjvJ0TJ0',
    appId: '1:833914734243:web:062e93debfc4c864b76116',
    messagingSenderId: '833914734243',
    projectId: 'flutter-projects-b9531',
    authDomain: 'flutter-projects-b9531.firebaseapp.com',
    storageBucket: 'flutter-projects-b9531.firebasestorage.app',
    measurementId: 'G-1L4EQH4MS6',
  );
}
